#ddev-generated
RUN curl -fsSL https://tailscale.com/install.sh | sh

ARG username
RUN mkdir -p /var/lib/tailscale && chown -R ${username}:${username} /var/lib/tailscale
RUN mkdir -p /var/run/tailscale && chown -R ${username}:${username} /var/run/tailscale
COPY start-tailscaled.sh /usr/local/bin/start-tailscaled.sh
RUN chmod +x /usr/local/bin/start-tailscaled.sh
