#ddev-generated
# This configuration adds Tailscale routing capabilities to the web container.
web_extra_daemons:
  - name: tailscale-service
    command: "/usr/local/bin/start-tailscaled.sh"
    directory: /usr/sbin

hooks:
  pre-stop:
    - exec: tailscale logout || true
